name: resources for deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-prediction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-prediction-service
  template:
    metadata:
      labels:
        app: churn-prediction-service
    spec:
      containers:
      - name: churn-prediction-service-container
        image: asia-south1-docker.pkg.dev/data-science-project-418009/dockerregistry/churn-prediction-service:${{ github.sha }}
        ports:
        - containerPort: 8080