name: churn-prediction-service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: neemar
          service_account_key: ${{ secrets.GKE_SECRET_CPS }}
          export_default_credentials: true

      - name: Configure Docker to use GCR
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/neemar/churn-prediction-service:${{ github.sha }} .
          docker push gcr.io/neemar/churn-prediction-service:${{ github.sha }}

      - name: Deploy to GKE
        uses: google-github-actions/deploy-gke@main
        with:
          credentials: ${{ secrets.GKE_SECRET_CPS }}
          project_id: data-science-project
          cluster: autopilot-cluster-1
          zone: asia-south1
          manifest: ./github/workflows/deploy.yaml
          image_tag: ${{ github.sha }}
