name: churn-prediction-service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com | bash
          exec -l $SHELL
          gcloud --version

      - name: Authenticate with Google Cloud and install kubectl
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GKE_SECRET-CPS}}
          project_id: data-science-project-418009
          export_default_credentials: true
          kubeconfig: ${{ runner.workspace }}/kubeconfig
          # echo "${{ secrets.GKE_SECRET_CPS }}" | base64 --decode > gcp-sa-key.json
          # gcloud auth activate-service-account --key-file=gcp-sa-key.json
          # gcloud projects add-iam-policy-binding data-science-project --member=serviceAccount:sample-service-account@data-science-project-418009.iam.gserviceaccount.com --role=roles/storage.objectViewer
          
        # env:
        #   GOOGLE_APPLICATION_CREDENTIALS: gcp-sa-key.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: neemar
          # service_account_key: ${{ secrets.GKE_SECRET_CPS }}
          # export_default_credentials: true

      - name: Let's copy gcp credentials
        run: echo "${{secrets.GKE_SECRET_CPS}}"  | base64 --decode > gcp_credentials.json

      - name: Configure Docker to use GCR
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev
      
      - name: Build and Push Docker image
        run: |
          docker build -t asia-south1-docker.pkg.dev/data-science-project-418009/dockerregistry/churn-prediction-service:${{ github.sha }} .
          docker push asia-south1-docker.pkg.dev/data-science-project-418009/dockerregistry/churn-prediction-service:${{ github.sha }}
      
      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --zone asia-south1 --project data-science-project-418009

      - name: Deploy to GKE
        run: |
          kubectl apply -f ./infra/kubernetes/resources.yaml
