name: churn-prediction-service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: neemar
          service_account_key: ${{ secrets.GKE_SECRET_CPS }}
          export_default_credentials: true

      - name: Let's copy gcp credentials
        run: echo "${{secrets.GKE_SECRET_CPS}}" > gcp_credentials.json

      - name: Authenticate with Google Cloud
        run: |
          echo ${{ secrets.GKE_SECRET_CPS }} > gcp-sa-key.json
          gcloud auth activate-service-account --key-file=gcp-sa-key.json

      - name: Configure Docker to use GCR
        run: |
          gcloud auth configure-docker
      
      - name: Grant Storage Object Viewer Role
        run: |
          gcloud projects add-iam-policy-binding data-science-project --member=serviceAccount:sample-service-account@data-science-project-418009.iam.gserviceaccount.com --role=roles/storage.objectViewer

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/neemar/churn-prediction-service:${{ github.sha }} .
          docker push gcr.io/neemar/churn-prediction-service:${{ github.sha }}

      - name: Install Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com | bash
          exec -l $SHELL
          gcloud --version
      
      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --zone asia-south1 --project data-science-project

      - name: Deploy to GKE
        run: |
          kubectl apply -f ./github/workflows/deploy.yaml